# Generated by Django 4.2.7 on 2024-07-24 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_img_alter_video_embedid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noti',
            name='students',
        ),
        migrations.AddField(
            model_name='noti',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='noti_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
