# Generated by Django 4.2.7 on 2024-07-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_noti_students_noti_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comm',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.URLField(default='https://ngheluatsu.com/resize-image/350x400/Avatar/avatar.jpg', max_length=700),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
