# Generated by Django 4.1.5 on 2023-09-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
