# Generated by Django 4.1.5 on 2023-09-04 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySphere', '0003_remove_comment_video_comment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_usr', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
