# Generated by Django 4.1.5 on 2023-09-04 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySphere', '0005_alter_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_usr', to=settings.AUTH_USER_MODEL)),
                ('video', models.ManyToManyField(blank=True, related_name='saved_vid', to='StudySphere.video')),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
