# Generated by Django 4.1.5 on 2023-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySphere', '0006_save_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='class_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
