# Generated by Django 4.1.5 on 2023-09-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySphere', '0007_video_class_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
